import type { Metadata } from "next";
import { Instrument_Serif, Baskervville } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import GlobalMouseTracker from "@/components/mouse-tracker";
import Navbar from "@/components/Navbar";

const instrumentSerif = Instrument_Serif({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-instrument-serif",
});

const baskerville = Baskervville({
  variable: "--font-baskerville",
  subsets: ["latin"],
});

const ppMontreal = localFont({
  src: "../public/fonts/ppneuemontreal-medium.otf",
  variable: "--font-pp-montreal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instrumentSerif.variable} ${ppMontreal.variable} ${baskerville.variable} antialiased`}
      >
        <GlobalMouseTracker>
          <Navbar />
          {children}
        </GlobalMouseTracker>
      </body>
    </html>
  );
}
